<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
return [
    // Retrieve list of modules used in this application.
    'modules' => [
        'Zend\\Cache',
        'Zend\\Db',
        'Zend\\Filter',
        'Zend\\Hydrator',
        'Zend\\InputFilter',
        'Zend\\I18n',
        'Zend\\Log',
        'Zend\\Mvc\\I18n',
        'Zend\\Paginator',
        'Zend\\Router',
        'Zend\\Validator',
        'Zend\\Cache',
        'Zend\\Db',
        'Zend\\Filter',
        'Zend\\Hydrator',
        'Zend\\InputFilter',
        'Zend\\I18n',
        'Zend\\Log',
        'Zend\\Mvc\\I18n',
        'Zend\\Paginator',
        'Zend\\Router',
        'Zend\\Validator',
        'Zend\\Cache',
        'Zend\\Db',
        'Zend\\Filter',
        'Zend\\Hydrator',
        'Zend\\InputFilter',
        'Zend\\I18n',
        'Zend\\Log',
        'Zend\\Mvc\\I18n',
        'Zend\\Paginator',
        'Zend\\Router',
        'Zend\\Validator',
        'Zend\\Cache',
        'Zend\\Db',
        'Zend\\Filter',
        'Zend\\Hydrator',
        'Zend\\InputFilter',
        'Zend\\I18n',
        'Zend\\Log',
        'Zend\\Mvc\\I18n',
        'Zend\\Paginator',
        'Zend\\Router',
        'Zend\\Validator',
        'Zend\\Cache',
        'Zend\\Db',
        'Zend\\Filter',
        'Zend\\Hydrator',
        'Zend\\InputFilter',
        'Zend\\I18n',
        'Zend\\Log',
        'Zend\\Mvc\\I18n',
        'Zend\\Paginator',
        'Zend\\Router',
        'Zend\\Validator',
        'Zend\\Db',
        'Zend\\Filter',
        'Zend\\Hydrator',
        'Zend\\InputFilter',
        'Zend\\Paginator',
        'Zend\\Router',
        'Zend\\Validator',
        'ZF\\Apigility',
        'ZF\\Apigility\\Documentation',
        'ZF\\ApiProblem',
        'ZF\\Configuration',
        'ZF\\OAuth2',
        'ZF\\MvcAuth',
        'ZF\\Hal',
        'ZF\\ContentNegotiation',
        'ZF\\ContentValidation',
        'ZF\\Rest',
        'ZF\\Rpc',
        'ZF\\Versioning',
        'ZF\\Apigility\\Documentation\\Swagger',
        'ZfrCors',
        'MSBios\\Filter',
        'MSBios\\Apigility',
    ],
    'module_listener_options' => [
        'module_paths' => [
            './module',
            './vendor',
        ],
        'config_glob_paths' => [
            realpath(__DIR__) . '/autoload/{{,*.}global,{,*.}local}.php',
        ],
        'config_cache_enabled' => false,
        // 'config_cache_key' => 'application.config.cache',
        'module_map_cache_enabled' => false,
        // 'module_map_cache_key' => 'application.module.cache',
        'cache_dir' => 'data/cache/',
    ],
];
